"""
Create a stratified sample for manual annotation.

This script samples examples from the support dataset and creates an
annotation file. Gold labels are NOT generated by this script.

The final golden set is manually reviewed and labeled according to
data/golden/labeling_guide.md.
"""

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.config import INTENTS, PAIRS_PATH, RANDOM_SEED
from src.intent.rules import rule_based_intent

N_PER_STRATUM = 30

ANNOTATION_PATH = Path("data/golden/golden_set_to_label.csv")


def main():
    pairs = pd.read_csv(PAIRS_PATH)

    # Production rules are used ONLY to create a balanced sampling pool.
    # They are NOT used as ground-truth labels.
    pairs["_stratum"] = (
        pairs["customer_text"]
        .fillna("")
        .map(rule_based_intent)
    )

    parts = []

    for intent in INTENTS:
        pool = pairs[pairs["_stratum"] == intent]

        n = min(N_PER_STRATUM, len(pool))

        if n > 0:
            parts.append(
                pool.sample(
                    n=n,
                    random_state=RANDOM_SEED
                )
            )

    sample = (
        pd.concat(parts)
        .drop_duplicates(subset=["customer_text"])
        .reset_index(drop=True)
    )

    # Create rows for manual annotation.
    # Gold labels are intentionally left blank.
    golden = pd.DataFrame({
        "customer_text": sample["customer_text"],
        "historical_agent_reply": sample["agent_text"],
        "gold_intent": "",
        "gold_escalate": "",
        "gold_escalation_reason": "",
    })

    ANNOTATION_PATH.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    golden.to_csv(
        ANNOTATION_PATH,
        index=False
    )

    print(
        f"Wrote {len(golden)} examples for manual annotation "
        f"-> {ANNOTATION_PATH}"
    )

    print("\nIMPORTANT:")
    print(
        "This file contains NO automatically generated gold labels."
    )
    print(
        "Manually review and label the examples, then save the "
        "completed file as data/golden/golden_set.csv"
    )


if __name__ == "__main__":
    main()